# Generated by Django 3.1.12 on 2025-11-17 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id_customer', models.CharField(max_length=64, unique=True, verbose_name='Job ID (From Customer)')),
                ('system_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('instruction', models.TextField(max_length=10000)),
                ('amount_inr', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expected_deadline', models.DateTimeField()),
                ('strict_deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('archived', 'Archived')], default='new', max_length=32)),
                ('is_superadmin_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='JobAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='jobs.job')),
            ],
        ),
        migrations.CreateModel(
            name='JobContentSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('summary', 'Job Summary'), ('structure', 'Job Structure'), ('content', 'Content'), ('referencing', 'Referencing'), ('plag_report', 'Plag Report'), ('ai_report', 'AI Report'), ('full_content', 'Full Content')], max_length=32)),
                ('content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('generated', 'Generated'), ('regenerate', 'Needs Regeneration'), ('approved', 'Approved')], default='waiting', max_length=32)),
                ('regeneration_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='jobs.job')),
            ],
            options={
                'ordering': ('section_type',),
                'unique_together': {('job', 'section_type')},
            },
        ),
    ]
