# Generated by Django 3.1.12 on 2025-11-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_add_ticket_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementsystem',
            name='key',
            field=models.CharField(choices=[('signup_login', 'Signup & Login Management'), ('profile_management', 'Profile Management'), ('user_management', 'User Management'), ('website_content', 'Website Content Management'), ('ticket_management', 'Ticket Management')], max_length=64, unique=True),
        ),
    ]
