# Generated by Django 3.1.12 on 2025-11-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('marketing', 'Marketing Team'), ('super_admin', 'Super Admin'), ('co_super_admin', 'Co Super Admin')], db_index=True, max_length=32)),
                ('label', models.CharField(max_length=128)),
                ('url_name', models.CharField(max_length=128)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('badge_key', models.CharField(blank=True, help_text="Nav count key like 'marketing.new_jobs' or 'superadmin.user_approvals'.", max_length=64)),
            ],
            options={
                'ordering': ('role', 'order', 'id'),
            },
        ),
    ]
