# Generated by Django 3.1.12 on 2025-11-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbuilder', '0004_add_pagebuilder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationitem',
            name='role',
            field=models.CharField(choices=[('marketing', 'Marketing Team'), ('super_admin', 'Super Admin'), ('co_super_admin', 'Co Super Admin'), ('global', 'Global User'), ('floor', 'Floor User')], db_index=True, max_length=32),
        ),
    ]
