# Generated by Django 3.1.12 on 2025-11-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileupdaterequest',
            name='request_type',
            field=models.CharField(choices=[('profile_picture', 'Profile Picture'), ('first_name', 'First Name'), ('last_name', 'Last Name'), ('whatsapp', 'WhatsApp No'), ('last_qualification', 'Last Qualification')], max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='First Name', max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text='Last Name', max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('marketing', 'Marketing Team'), ('super_admin', 'Super Admin'), ('co_super_admin', 'Co Super Admin')], default='marketing', max_length=32),
        ),
    ]
