# Generated by Django 3.1.12 on 2025-11-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_floor_creds_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login_country',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_timezone',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
