# Generated by Codex on 2025-11-26
from django.db import migrations, models
import django.db.models.deletion
from decimal import Decimal


def seed_gems_for_existing_globals(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    GemsAccount = apps.get_model("accounts", "GemsAccount")
    GemTransaction = apps.get_model("accounts", "GemTransaction")
    for user in User.objects.filter(role="global"):
        account, created = GemsAccount.objects.get_or_create(user=user)
        if created and account.balance == 0:
            account.balance = Decimal("50")
            account.save(update_fields=["balance"])
            GemTransaction.objects.create(
                user=user,
                amount=Decimal("50"),
                reason="Welcome bonus (existing global user)",
                created_by=None,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_auto_20251125_1713"),
    ]

    operations = [
        migrations.CreateModel(
            name="GemsAccount",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("balance", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="gems_account", to="accounts.user")),
            ],
        ),
        migrations.CreateModel(
            name="GemTransaction",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("reason", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="gem_transactions_created", to="accounts.user")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="gem_transactions", to="accounts.user")),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.RunPython(seed_gems_for_existing_globals, migrations.RunPython.noop),
    ]
