# Generated by Django 3.1.12 on 2025-11-27 06:21

import bson.objectid
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_gems_models'),
    ]

    # Djongo cannot ALTER an existing field type; apply state change only.
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='gemsaccount',
                    name='id',
                    field=djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False),
                ),
            ],
        )
    ]
