# Generated by Django 3.1.12 on 2025-11-20 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('allowed_roles', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField()),
                ('label', models.CharField(max_length=128)),
                ('help_text', models.CharField(blank=True, max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('number', 'Number'), ('date', 'Date'), ('datetime', 'DateTime'), ('select', 'Select'), ('file', 'File')], default='text', max_length=32)),
                ('order', models.PositiveIntegerField(default=0)),
                ('required_roles', models.JSONField(blank=True, default=list)),
                ('visible_roles', models.JSONField(blank=True, default=list)),
                ('read_only_roles', models.JSONField(blank=True, default=list)),
                ('choices', models.JSONField(blank=True, default=list)),
                ('target_field', models.CharField(help_text='Model field this config controls (e.g., job_id_customer).', max_length=128)),
                ('is_system', models.BooleanField(default=False, help_text='System fields are shown for reference and cannot be removed.')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='formbuilder.formdefinition')),
            ],
            options={
                'ordering': ('order', 'id'),
                'unique_together': {('definition', 'name')},
            },
        ),
    ]
