# Generated by Django 3.1.12 on 2025-11-20 06:20

from django.db import migrations, models
import tickets.models


def populate_ticket_ids(apps, schema_editor):
    Ticket = apps.get_model("tickets", "Ticket")
    for ticket in Ticket.objects.all():
        if ticket.ticket_id:
            continue
        ticket_id = tickets.models.generate_ticket_id()
        while Ticket.objects.filter(ticket_id=ticket_id).exists():
            ticket_id = tickets.models.generate_ticket_id()
        ticket.ticket_id = ticket_id
        ticket.save(update_fields=["ticket_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(blank=True, editable=False, max_length=24, null=True),
        ),
        migrations.RunPython(populate_ticket_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(db_index=True, default=tickets.models.generate_ticket_id, editable=False, max_length=24),
        ),
    ]
