# Generated by Django 3.1.12 on 2025-11-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_category_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('technical', 'Technical'), ('other', 'Other'), ('deadline_change', 'Deadline Change')], default='general', max_length=32),
        ),
    ]
